stages:
  - build
  - execute

build:
  stage: build
  tags:
     - java-ci
  script: mvn clean install
  artifacts:
    paths:
     - target/Alien_JPA-0.war
execute:
  stage: execute
  tags:
     - java-ci
  script: mvn spring-boot:run
