stages:
  - build
  - execute

build:
  stage: build
  tags:
     - java-ci
  script: mvn clean install
  artifacts:
    paths:
     - target/

test:
  stage: test
  tags:
     - java-ci
  script: mvn spring-boot:run
